"""initial schema

Revision ID: 4de39ca31067
Revises: 
Create Date: 2026-04-21 17:36:08.974701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4de39ca31067'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('aoi_bbox', sa.JSON(), nullable=False),
    sa.Column('date_range', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('agent_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('agent', sa.String(), nullable=False),
    sa.Column('replan_count', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gedi_shots_cleaned',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('shot_id', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('rh98', sa.Float(), nullable=True),
    sa.Column('b2', sa.Float(), nullable=True),
    sa.Column('b3', sa.Float(), nullable=True),
    sa.Column('b4', sa.Float(), nullable=True),
    sa.Column('b8', sa.Float(), nullable=True),
    sa.Column('b11', sa.Float(), nullable=True),
    sa.Column('b12', sa.Float(), nullable=True),
    sa.Column('ndvi', sa.Float(), nullable=True),
    sa.Column('evi', sa.Float(), nullable=True),
    sa.Column('fold', sa.Integer(), nullable=True),
    sa.Column('split', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gedi_shots_raw',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('shot_id', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('rh98', sa.Float(), nullable=True),
    sa.Column('sensitivity', sa.Float(), nullable=True),
    sa.Column('slope', sa.Float(), nullable=True),
    sa.Column('beam', sa.String(), nullable=True),
    sa.Column('quality_flag', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gedi_shots_raw')
    op.drop_table('gedi_shots_cleaned')
    op.drop_table('agent_decisions')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
